//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePower
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int NodeId { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Function Function { get; set; }
        public virtual Role Role { get; set; }
    }
}
